[build]
builder = "nixpacks"

[deploy]
startCommand = "mix phx.server"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PHX_SERVER = "true"
POOL_SIZE = "10"
